# Import libraries

In [1]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import time

# Fetch Data

In [2]:
# Read data from the CSV for California hospitals
cal_detail = pd.read_csv('../data/raw/California/CA - Final_PRA_29194 - 2026-04-08.xlsx - Detail.csv')
cal_geocode = pd.read_csv('../data/handmade/California/California_Hospital_Geocodes.csv')

# Read data from the CSV files for Colorado Hospitals
col_detail = pd.read_csv('../data/raw/Colorado/CO - Data_Request_-_Michael_Nolan-_03.30.2026_-_Facility_Occurrences_CY_23-25xlsx.xlsx - Data.csv')
col_geocode = pd.read_csv('../data/handmade/Colorado/Colorado_Hospital_Geocodes.csv')

# Read data from the CSV files for Washington Hospitals
wa_detail = pd.read_csv("../data/raw/Washington/WA-downloadable_ae - 2026-04-07.csv")
wa_geocode = pd.read_excel("../data/raw/Washington/Facilities.xlsx")

# Merge California data with their Geocodes

### Merge the data

In [ ]:
cal_detail['ASPEN_FACID'] = cal_detail['ASPEN_FACID'].astype(str).str.strip()
cal_geocode['ASPEN_FACID'] = cal_geocode['ASPEN_FACID'].astype(str).str.strip()

# FIX: deduplicate on ASPEN_FACID to prevent row inflation
cal_geo_dedup = (
    cal_geocode[['ASPEN_FACID', 'LATITUDE', 'LONGITUDE']]
    .drop_duplicates(subset=['ASPEN_FACID'])
    .rename(columns={'LATITUDE': 'LAT', 'LONGITUDE': 'LON'})
)

cal_merged = cal_detail.merge(cal_geo_dedup, on='ASPEN_FACID', how='left')
cal_merged.head()

,INTAKEID,RECVDATE,AE_CATEGORY,AE_SHORT,ADVERSE_EVENT,FINDING_DETAIL,ASPEN_FACID,NAME,ASPEN_FACTYPE_LABEL,LAT,LON
0,CA00819364,4-Jan-23,04 - Care Management Events,17: Stage 3/4 Pressure Ulcer,"17: Stage 3 or 4 Pressure Ulcer, Acquired Afte...",Z2_Missing,CA220000019,ZUCKERBERG SAN FRANCISCO GENERAL HOSP & TRAUMA...,General Acute Care Hospital,37.756161,-122.405665
1,CA00819439,4-Jan-23,04 - Care Management Events,17: Stage 3/4 Pressure Ulcer,"17: Stage 3 or 4 Pressure Ulcer, Acquired Afte...",Z2_Missing,CA030000901,MERCY HOSPITAL OF FOLSOM,General Acute Care Hospital,38.670210,-121.145382
2,CA00819831,9-Jan-23,04 - Care Management Events,17: Stage 3/4 Pressure Ulcer,"17: Stage 3 or 4 Pressure Ulcer, Acquired Afte...",Z2_Missing,CA030000123,MEMORIAL MEDICAL CENTER,General Acute Care Hospital,37.668762,-120.974656
3,CA00820220,9-Jan-23,04 - Care Management Events,17: Stage 3/4 Pressure Ulcer,"17: Stage 3 or 4 Pressure Ulcer, Acquired Afte...",Z2_Missing,CA220000031,UCSF MEDICAL CENTER,General Acute Care Hospital,37.784381,-122.439627
4,CA00820763,11-Jan-23,04 - Care Management Events,17: Stage 3/4 Pressure Ulcer,"17: Stage 3 or 4 Pressure Ulcer, Acquired Afte...",Z2_Missing,CA030000901,MERCY HOSPITAL OF FOLSOM,General Acute Care Hospital,38.670210,-121.145382

### Save CSV

In [ ]:
cal_merged.to_csv("../data/processed/California/CA-Hospital Data with Geocodes.csv", index=False)

# Merge Colorado data with their Geocodes

### Merge the data

In [ ]:
col_detail['Facility ID'] = col_detail['Facility ID'].astype(str).str.strip()
col_geocode['Facility_ID'] = col_geocode['Facility_ID'].astype(str).str.strip()

col_geo_slim = (
    col_geocode[['Facility_ID', 'LAT', 'LON']]
    .rename(columns={'Facility_ID': 'Facility ID'})
)

col_merged = col_detail.merge(col_geo_slim, on='Facility ID', how='left')
col_merged.head()

,Facility ID,Facility Name,Facility Type Code,Facility Type Name,Facility Type Abbreviation,Facility Admin Name,Bed License Total,Owner Company,Facility Operating Status,Facility Address,Facility County,Facility City,Facility Phone,Occurrence ID,Type of Occurrence,Occurrence Date,Occurrence Description,Occurrence Description_Overflow1,LAT,LON
0,10C962,# 1 HOME CARE AGENCY CORPORATION,05D,Home Care Agency-Personal Care/Homemaker (Medi...,HCA-PHS,"Vaynshteyn, Samuil",0,# 1 HOME CARE AGENCY CORPORATION,Active,"10200 E GIRARD AVE BLDG A STE 103, DENVER, CO...",Denver,DENVER,(303) 306-0404,2310C962001,Misappropriation of Property,4/24/2023,"DESCRIPTION OF OCCURRENCE: On 4/24/23, a clie...",NaN,39.656151,-104.868362
1,0506AT,198 E GALATEA,S41,Residential Care Facility for the Developmenta...,RCF-DD,"De Maria, Jacqueline (JR)",8,STATE OF COLORADO,Active,"198 E GALATEA DR, PUEBLO WEST, CO 81007-",Pueblo,PUEBLO WEST,(719) 585-4001,230506AT001,Neglect,3/14/2023,"DESCRIPTION OF OCCURRENCE: On 3/14/23, a staf...",NaN,38.324306,-104.734924
2,0506AT,198 E GALATEA,S41,Residential Care Facility for the Developmenta...,RCF-DD,"De Maria, Jacqueline (JR)",8,STATE OF COLORADO,Active,"198 E GALATEA DR, PUEBLO WEST, CO 81007-",Pueblo,PUEBLO WEST,(719) 585-4001,230506AT002,Physical Abuse,3/21/2023,"DESCRIPTION OF OCCURRENCE: On 3/21/23, staff ...",NaN,38.324306,-104.734924
3,0506AT,198 E GALATEA,S41,Residential Care Facility for the Developmenta...,RCF-DD,"De Maria, Jacqueline (JR)",8,STATE OF COLORADO,Active,"198 E GALATEA DR, PUEBLO WEST, CO 81007-",Pueblo,PUEBLO WEST,(719) 585-4001,230506AT003,Physical Abuse,3/27/2023,DESCRIPTION OF OCCURRENCE: On 3/27/23 during ...,NaN,38.324306,-104.734924
4,0506AT,198 E GALATEA,S41,Residential Care Facility for the Developmenta...,RCF-DD,"De Maria, Jacqueline (JR)",8,STATE OF COLORADO,Active,"198 E GALATEA DR, PUEBLO WEST, CO 81007-",Pueblo,PUEBLO WEST,(719) 585-4001,230506AT004,Physical Abuse,5/8/2023,"DESCRIPTION OF OCCURRENCE: On 5/8/23, staff r...",NaN,38.324306,-104.734924

### Save CSV

In [ ]:
col_merged.to_csv("../data/processed/Colorado/CO-Hospital Data with Geocodes.csv", index=False)

# Merge Washington data with their Geocodes

## Get the locations and use Google Maps API to fetch geocodes and merge them

In [6]:
# KEEP ONLY REQUIRED COLUMNS
wa_geocode = wa_geocode[
    [
        "Credential Number",
        "Facility: Mailing Address"
    ]
]

# Remove duplicate credential numbers
wa_geocode = wa_geocode.drop_duplicates(
    subset="Credential Number"
)

# LEFT MERGE
merged_df = wa_detail.merge(
    wa_geocode,
    left_on="Facility Credential",
    right_on="Credential Number",
    how="left"
)

assert len(wa_detail) == len(merged_df), \
    "ERROR: Row count changed after merge!"

# INITIALIZE GEOPY
geolocator = Nominatim(
    user_agent="hospital_geocoder",
    timeout=10
)


# Nominatim usage policy recommends no more than 1 request/second.
geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1.5,
    max_retries=3,
    error_wait_seconds=10
)

# GEOCODE FUNCTION
def get_coordinates(address):

    if pd.isna(address):
        return (None, None)

    address = str(address).strip()

    if address == "":
        return (None, None)

    try:
        location = geocode(address)

        if location is None:
            return (None, None)

        return (
            location.latitude,
            location.longitude
        )

    except Exception as e:
        print(f"Error geocoding:\n{address}\n{e}")
        return (None, None)

# GEOCODE ONLY UNIQUE ADDRESSES
unique_addresses = (
    merged_df["Facility: Mailing Address"]
    .dropna()
    .unique()
)

print(f"\nUnique addresses to geocode: {len(unique_addresses)}")

geocode_cache = {}

for i, address in enumerate(unique_addresses, start=1):
    geocode_cache[address] = get_coordinates(address)
    if i % 50 == 0:
        print(f"Processed {i}/{len(unique_addresses)} addresses")

print("Geocoding complete.")

# ADD LATITUDE AND LONGITUDE
merged_df["LAT"] = merged_df["Facility: Mailing Address"].map(
    lambda x: geocode_cache.get(x, (None, None))[0]
)
merged_df["LON"] = merged_df["Facility: Mailing Address"].map(
    lambda x: geocode_cache.get(x, (None, None))[1]
)

# VERIFY ROW COUNT
assert len(wa_detail) == len(merged_df), \
    "ERROR: Row count changed after geocoding!"

print(f"Final row count: {len(merged_df)}")

Unique addresses to geocode: 142
Processed 50/142 addresses
Processed 100/142 addresses
Geocoding complete.
Final row count: 188160

## Save CSV

In [6]:
merged_df.to_csv("../data/processed/Washington/WA-Hospital Data with Geocodes.csv", index=False)

In [12]:
# Get unique facility names where LAT is null
temp_df = merged_df[merged_df['LAT'].isnull()]
null_lat_facilities = temp_df['Facility Name'].unique()
null_lat_ids = temp_df['Facility Credential'].dropna().unique()

print(f"Total number of facilities: {merged_df['Facility Credential'].nunique()} \
\nTotal number of facilities without geocodes: {temp_df['Facility Credential'].nunique()} \
\nTotal number of facilities with geocodes: {int(merged_df['Facility Credential'].nunique())-int(temp_df['Facility Credential'].nunique())}")
print(null_lat_facilities)
print("="*30)
print(null_lat_ids)

Total number of facilities: 489
Total number of facilities without geocodes: 351
Total number of facilities with geocodes: 138
['Acute Pain Therapies' 'Advanced Dermatology and Skin Surgery'
 'Advanced Endoscopy Center dba Salmon Creek Surgery Center'
 'Aesthetic and General Dermatology of Seattle'
 'Aesthetic Facial Body Plastic Surgery'
 'Aesthetic Plastic Surgical Center'
 'Aesthetic Surgery Centre and Med Spa' 'Aesthetica Clinique LLC'
 'Ageless' 'Allure Esthetic' 'Allure Laser Center'
 'Allure Laser Center and Medispa' 'Amadi Aesthetics Plastic Surgery'
 'Anderson Sobel Cosmetic Surgery' 'Anesis Bel-Red ASC, LLC'
 'Anesis Spokane ASC' 'Apex Spine ASC' 'Arlington Surgery Center'
 'Artistic Plastic Surgery Center' 'ASC/Endoscopy Center'
 'Athenix Advanced Plastic Surgery and Aesthetic Centers'
 'Auburn Surgery Center' 'Avalon Clinic' 'Aysel K Sanderson MD'
 'Bel Red Ambulatory Surgical Facility' 'Bellevue Plastic Surgery Center'
 'Bellevue Surgery Center' 'Bellingham Ambulatory Surgery Center'
 'Bellingham Surgery Center' 'Bellingham Urology Group PLLC'
 'Bellingham Urology Specialists' 'Capitol Hill Ambulatory Surgery Center'
 'Cascade Ear Nose and Throat Surgery Center' 'Cascade ENT Surgery Center'
 'Cascade Laser & Surgery Center' 'Cascade Outpatient Spine Center'
 'Cascade Surgery Center' 'Cascade Valley Arlington Surgery Center'
 'Cascadia Surgical'
 'Chesnut Institute of Cosmetic and Reconstructive Surgery PLLC'
 'Columbia Surgery Center' 'Columbia Surgery Center, LLC'
 'Confluence Health - Moses Lake Ambulatory Surgical Center'
 'Confluence Health - Moses Lake Clinic'
 'Confluence Health - Omak Ambulatory Surgical Facility'
 'Confluence Health - Omak Clinic' 'Confluence Health Moses Lake Clinic'
 'Confluence Health Omak Clinic'
 'Cosmetic Surgery and Dermatology of Issaquah'
 'Cosmetic Surgical Arts Center'
 'Digestive Disease and Endoscopy Center LLC'
 'Direct Imaging Ambulatory Surgery Center' 'Dr. Vincent Muoneke, MD'
 'Ear Nose and Throat Clinic of the Northwest'
 'Ear, Nose, Throat, Facial Plastic Surgery and Allergy of Western Washington Inc PS'
 'Eastside Endoscopy Center' 'Eastside Endoscopy Center - Issaquah'
 'Eastside Surgery Center' 'Edmonds Endoscopy Center'
 'Egrari Plastic Surgery Center' 'Empire Eye Physicians'
 'Empire Eye Surgery Center' 'Evergreen Endoscopy Center'
 'Evergreen Endoscopy Center - Kirkland' 'Evergreen Eye Center'
 'Evergreen Eye Center - Seattle' 'Evergreen Eye Center - Tacoma'
 'Evergreen Surgical Center'
 'Evergreen Surgical Clinic Ambulatory Surgery Center'
 'EvergreenHealth Ambulatory Surgical Care' 'EVIVA' 'EVIVA-Edmonds'
 'Eye Associates Northwest Surgery Center'
 'Eye Associates NW Nordstrom Ambulatory Surgery Center'
 'Eye Surgery of Edmonds' 'Federal Way Ambulatory Surgical Facility'
 'First Hill Surgery Center' 'Fogel Endoscopy'
 'Foley Plastic Surgery Center' 'Fremont Endoscopy Center'
 'Gaboriau Center' 'Gastro Health'
 'Gastroenterology Associates Endoscopy Center' 'Gateway Surgery Center'
 'Hand and Wrist Surgery Center of Washington'
 'Harbor Plastic Surgery Center' 'High Desert Surgery Center'
 'Hillside Medical Surgery Center' 'Hoyeol Yang MD PS'
 'Inland Empire Endoscopy Center' 'Inland Northwest Surgery Center'
 'John H Brunsman DPM PS' 'Kadlec Ambulatory Endoscopy Center, Lee Campus'
 'Kadlec Ambulatory Surgery Center - Spaulding Campus'
 'Kaiser Permanente Ambulatory Surgery Center'
 'Kaiser Permanente Capitol Hill Procedure Center'
 'Kaiser Permanente Tacoma Ambulatory Surgery Center'
 'la Belle Vie Cosmetic Surgery Centers' 'Laser and Surgery Center LLC'
 'Liebertz Plastic Surgery at Yarrow Bay' 'Madison Tower Surgery Center'
 'Maple Valley Surgical Arts' 'Marina Park Plastics'
 'Medical Center at PRO Sports Club' 'Meridian Surgery Center'
 'Michael Workman Plastic Surgery' 'Microsurgical Spine Center'
 'Mid-Columbia Endoscopy Center' 'Minor and James Endoscopy Center'
 'MultiCare Rockwood Eye Surgery Center'
 'MultiCare Surgery Center - Auburn'
 'MultiCare Yakima Ambulatory Surgery Center'
 'MultiCare Puyallup Ambulatory Surgery Center'
 'Naficy Plastic Surgery and Rejuvenation Center'
 'Narrows Eye Surgery Center' 'NEOS Surgery Center'
 'North Seattle Surgery Center' 'Northwest Ambulatory Physicians'
 'Northwest Center for Aesthetic Plastic Surgery'
 'Northwest Center For Plastic and Reconstructive Surgery'
 'Northwest Endoscopy Center' 'Northwest Endovascular Surgery'
 'Northwest Eye Surgeons' 'Northwest Eye Surgeons (Northgate)'
 'Northwest Eye Surgeons, Mount Vernon' 'Northwest Eye Surgeons, Renton'
 'Northwest Eye Surgeons, Seattle' 'Northwest Eye Surgeons, Sequim'
 'Northwest Glaucoma and Cataract' 'Northwest Laser and Surgery Center'
 'Northwest Orthopaedic Specialists' 'Northwest Surgery Center'
 'Northwest Weight Loss Surgery Center' 'NW Face and Body'
 'Olympia Multi Specialty Clinic Ambulatory Procedure Center'
 'Olympia Pain and Spine Surgery Center'
 'Olympia Surgery Center, Capital Mall'
 'Olympia Surgery Center, Lilly Road' 'Olympia Surgery Center, Tumwater'
 'Olympic Plastic Surgery Suite' 'Optum - Edmonds Surgery Center'
 'Optum - Kemp Surgery Center' 'Optum - Pumphrey Surgery Center'
 'Orthopedic International Ambulatory Surgery Center'
 'Overlake Reproductive Health Inc PS' 'Overlake Surgery Center'
 'Pacific Cataract and Laser Institute, Bellevue'
 'Pacific Cataract and Laser Institute, Bellingham'
 'Pacific Cataract and Laser Institute, Chehalis'
 'Pacific Cataract and Laser Institute, Kennewick'
 'Pacific Cataract and Laser Institute, Olympia'
 'Pacific Cataract and Laser Institute, Silverdale'
 'Pacific Cataract and Laser Institute, Spokane'
 'Pacific Cataract and Laser Institute, Spokane Valley'
 'Pacific Cataract and Laser Institute, Tacoma'
 'Pacific Cataract and Laser Institute, Vancouver'
 'Pacific Cataract and Laser Institute, Yakima' 'Pacific Gastro Health'
 'Pacific Northwest Center for Facial Plastic Surgery'
 'Pacific Northwest Eye Surgery Center'
 'Pacific Northwest Urology Surgery Center'
 'Pacific Rim Outpatient Surgery Center' 'Pacific Surgery Center'
 'Pacific Surgical Center' 'Pacmed Ambulatory Surgical Clinic'
 'Pain Care Physicians PLLC' 'Parkway Surgical Center'
 'PeaceHealth Medical Group Endoscopy Center'
 'PeaceHealth Squalicum Surgery Center' 'Pearl Plastic Surgery'
 'Peninsula Endoscopy Center' 'Phase Plastic Surgery'
 'Philip C. Kierney MD' 'Physicians Eye Surgery Center'
 'Plastic and Reconstructive Surgeons ASC'
 'Plastic Surgery Associates of Seattle' 'Plastic Surgery Bellingham'
 'Plastic Surgery North West Surgery Center'
 'Plastic Surgery Northwest Surgery Center' 'Premier Orthopedic Group'
 'PRO Medical Surgery Center'
 'Proliance Center for Outpatient Spine and Joint Surgery'
 'Proliance Center for Specialty Surgery'
 'Proliance Eastside Surgery Center'
 'Proliance Edmonds Center for Outpatient Surgery'
 'Proliance Everett Bone and Joint Surgery Center'
 'Proliance Highlands Surgery Center'
 'Proliance Hillside Medical Surgery Center'
 'Proliance Orthopedic Associates Ambulatory Surgery Center'
 'Proliance Puget Sound Surgery Center'
 'Proliance Skagit Northwest Orthopedic Surgery Center'
 'Proliance Southwest Seattle Surgery Center'
 'Proliance Surgeons Seattle Orthopedic Center - ASC'
 'Proliance Surgery Center at Rainier'
 'Proliance Surgery Center at Valley'
 'Providence Surgery and Procedure Center'
 'Providence Surgery Center, Pacific Campus' 'Puget Sound Plastic Surgery'
 'Puyallup Ambulatory Surgery Center' 'Puyallup Endoscopy Center'
 'Rainier Surgical Center' 'Rebound Surgery Center'
 'Redmond Ambulatory Surgery Center' 'Remington Plastic Surgery'
 'Ridgway Face & Aesthetic Center'
 'Rockwood Digestive Health and Endoscopy Services'
 'Rockwood Eye Surgery Center' 'RP Plastic Surgery'
 'Salmon Creek Plastic Surgery' 'Salmon Surgery Center'
 'Seattle Endoscopy Center' 'Seattle Facial Plastic Surgery Center'
 'Seattle Hand Surgery Group PC' 'Seattle Plastic Surgery Center'
 'Seattle Reproductive Surgery Center' 'Seattle Skin Cancer Center'
 'Seattle Spine Institute' 'Seattle Surgery Center'
 'Seattle Surgery Center LLC' 'Sequim Same Day Surgery'
 'Shape Cosmetic Surgery and Medspa' 'Sixth Avenue Surgery Center'
 'Skagit Northwest Orthopedics ASC at Continental' 'SoGab Surgery Center'
 'Sono Bello' 'Sono Bello - Tacoma' 'Sound Eye and Laser'
 'Sound Interventional Pain Management PLLC' 'Sound Plastic Surgery'
 'Sound Surgeons Surgery Center' 'Sound Urological Associates'
 'Soundview Ambulatory Surgery Center' 'South Perry Endoscopy'
 'South Sound Surgery Center' 'SouthLake Clinic'
 'Specialty Eyecare Centre' 'Spokane Digestive Disease Center'
 'Spokane Plastic Surgeons' 'Spokane Surgery Center'
 'Spokane Surgery Center, N Pines'
 'Spokane Valley Ambulatory Surgery Center' 'SRM Spokane'
 "St. Mark's Micro Surgery Center Inc" 'Stephens Plastic Surgery'
 'Sunrise Endoscopy Center' 'Surgery Center of Silverdale'
 'Tahoma Ambulatory Surgery Center' 'TASC'
 'The Doctors Clinic Ambulatory Surgery and Endoscopy Center'
 'The Doctors Clinic Ambulatory Surgery Center'
 'The Eye Surgeons Group Ambulatory Surgery Center'
 'The Gallery of Cosmetic Surgery' 'The Laser and Surgery Center'
 'The Polyclinic - Plastic Surgery Center'
 'The Polyclinic Surgery Endoscopy Centers' 'The Retina Surgery Center'
 'The Spokane Eye Surgery Center' 'The Stern Center for Aesthetic Surgery'
 'The Surgery Center at TCO' 'The Surgery Center at Tri-City Orthopaedic'
 'The Surgery Center at Tri-City Orthopaedic Clinic'
 'The Vancouver Clinic Surgery Center at Salmon Creek'
 'Transform Weight Loss' 'Trask Surgery Center'
 'Tri-Cities Endoscopy Center' 'Tri-City Regional Surgery Center'
 'Tukwila Ambulatory Surgery Center' 'Urology Northwest Surgery Center'
 'Urology Surgery Center Northwest' 'Valley MAC ASC'
 'Vancouver Clinic Endoscopy Center'
 'Vancouver Eye Care Surgery and Laser Center'
 'Virginia Mason Bellevue Ambulatory Surgery Center'
 'Virginia Mason Bellevue Ambulatory Surgical Center'
 'Virginia Mason Issaquah Medical Center'
 'Virginia Mason Lynnwood Medical Center' 'Waldron Endoscopy Center'
 'Walla Walla Clinic Ambulatory Surgery Center'
 'Washington Institute Orthopedic Center' 'Washington Orthopaedic Center'
 'Washington Spine Diagnostics and Treatment Center'
 'Washington Urology Associates PLLC'
 'Western Washington Medical Group - The Endoscopy Center'
 'Westwood Eye Surgery & Laser Center' 'Westwood Eye Surgery and Laser'
 'Whatcom Surgery Center' "Women's Health Connection"
 'Yakima Ambulatory Surgical Center' 'Yakima Gastroenterology Associates'
 'Yakima Urology Surgery Center'
 "The Greenbank Women's Clinic and Birth Center"
 'Puget Sound Midwives and Birth Center' 'Eastside Birth Center'
 'The Birthing Inn' 'Cascade Midwives and Birth Center'
 'Birthroot Midwives and Birth Center'
 'Puget Sound Midwives and Birth Center LLC' 'True North Birth Center'
 'Sprout Birth Center & Natural Health'
 'Moonrise Wellness and Birth Center' 'Greenbank Birth Center, PLLC'
 'Cascade Birth Center' 'The Special Delivery Birth Center LLC'
 'Community Birth Center' 'The Bridge Birth Center, LLC'
 'Columbia Birth Center' 'Rainier Valley Birth and Health Center'
 'Spokane River Birth Center' 'Mount Vernon Birth Center'
 'Klickitat Valley Health'
 'Mary Bridge Childrens Hospital and Health Center'
 'Odessa Memorial Healthcare Center' 'Skyline Hospital'
 'St Anthony Hospital' 'Three Rivers Hospital'
 'University of Washington Medical Center' 'Willapa Harbor Hospital'
 'Clallam Bay Corrections Center' 'Washington State Penitentiary'
 'Monroe Correctional Complex' 'Airway Heights Corrections Center'
 'Coyote Ridge Corrections Center' 'Washington Corrections Center'
 'Washington Corrections Center for Women'
 'Stafford Creek Corrections Center' nan]
==============================
['ASF.FS.61116093' 'ASF.FS.61439492' 'ASF.FS.60102980' 'ASF.FS.61057954'
 'ASF.FS.60280600' 'ASF.FS.60099259' 'ASF.FS.60429354' 'ASF.FS.60099487'
 'ASF.FS.60252056' 'ASF.FS.60629909' 'ASF.FS.60102702' 'ASF.FS.60851025'
 'ASF.FS.60099157' 'ASF.FS.60574719' 'ASF.FS.61635121' 'ASF.FS.60278641'
 'ASF.FS.61351695' 'ASF.FS.61499764' 'ASF.FS.61565925' 'ASF.FS.61287220'
 'ASF.FS.60651816' 'ASF.FS.60099774' 'ASF.FS.60100112' 'ASF.FS.60329939'
 'ASF.FS.60220028' 'ASF.FS.60102696' 'ASF.FS.60101705' 'ASF.FS.60102983'
 'ASF.FS.60320007' 'ASF.FS.60287715' 'ASF.FS.60102997' 'ASF.FS.61642947'
 'ASF.FS.60099795' 'ASF.FS.60550850' 'ASF.FS.60102503' 'ASF.FS.60619716'
 'ASF.FS.60442571' 'ASF.FS.60100987' 'ASF.FS.60102509' 'ASF.FS.60600948'
 'ASF.FS.60099142' 'ASF.FS.60101763' 'ASF.FS.60298280' 'ASF.FS.60776003'
 'ASF.FS.60099962' 'ASF.FS.61362533' 'ASF.FS.61433945' 'ASF.FS.60758153'
 'ASF.FS.61433969' 'ASF.FS.60758149' 'ASF.FS.60101689' 'ASF.FS.60101694'
 'ASF.FS.60100200' 'ASF.FS.60103023' 'ASF.FS.60287214' 'ASF.FS.61187358'
 'ASF.FS.60109662' 'ASF.FS.60106453' 'ASF.FS.60360678' 'ASF.FS.60100024'
 'ASF.FS.60262734' 'ASF.FS.60477711' 'ASF.FS.60282672' 'ASF.FS.61651433'
 'ASF.FS.60307710' 'ASF.FS.61135676' 'ASF.FS.61339788' 'ASF.FS.60100027'
 'ASF.FS.60103003' 'ASF.FS.70015764' 'ASF.FS.60099942' 'ASF.FS.60862319'
 'ASF.FS.61026553' 'ASF.FS.60100217' 'ASF.FS.60101044' 'ASF.FS.60584768'
 'ASF.FS.60501191' 'ASF.FS.60109922' 'ASF.FS.60102711' 'ASF.FS.60102990'
 'ASF.FS.60101644' 'ASF.FS.60919612' 'ASF.FS.60100114' 'ASF.FS.60641959'
 'ASF.FS.60100197' 'ASF.FS.60102721' 'ASF.FS.60101880' 'ASF.FS.61651468'
 'ASF.FS.60100119' 'ASF.FS.61252855' 'ASF.FS.60099811' 'ASF.FS.61032369'
 'ASF.FS.60100914' 'ASF.FS.60100931' 'ASF.FS.60278673' 'ASF.FS.60101793'
 'ASF.FS.60099270' 'ASF.FS.60292086' 'ASF.FS.60100035' 'ASF.FS.60107244'
 'ASF.FS.60102987' 'ASF.FS.61022929' 'ASF.FS.60788612' 'ASF.FS.60100954'
 'ASF.FS.60627140' 'ASF.FS.60100949' 'ASF.FS.60208682' 'ASF.FS.60101649'
 'ASF.FS.60312375' 'ASF.FS.60430558' 'ASF.FS.60102512' 'ASF.FS.61104390'
 'ASF.FS.60932741' 'ASF.FS.60100910' 'ASF.FS.60113911' 'ASF.FS.60101867'
 'ASF.FS.60301938' 'ASF.FS.60639491' 'ASF.FS.60833960' 'ASF.FS.60604663'
 'ASF.FS.61529296' 'ASF.FS.61498137' 'ASF.FS.60101790' 'ASF.FS.61002680'
 'ASF.FS.60417825' 'ASF.FS.60099949' 'ASF.FS.60109656' 'ASF.FS.60101127'
 'ASF.FS.60099243' 'ASF.FS.60099957' 'ASF.FS.61147863' 'ASF.FS.60528629'
 'ASF.FS.61186247' 'ASF.FS.61256745' 'ASF.FS.60264053' 'ASF.FS.60977760'
 'ASF.FS.60101742' 'ASF.FS.60977747' 'ASF.FS.60101724' 'ASF.FS.60977711'
 'ASF.FS.60101741' 'ASF.FS.60977737' 'ASF.FS.60685668' 'ASF.FS.60277121'
 'ASF.FS.60100039' 'ASF.FS.61316373' 'ASF.FS.60455333' 'ASF.FS.60099789'
 'ASF.FS.60118035' 'ASF.FS.60100042' 'ASF.FS.60790136' 'ASF.FS.60320652'
 'ASF.FS.61365265' 'ASF.FS.60100946' 'ASF.FS.60102740' 'ASF.FS.60701963'
 'ASF.FS.60100209' 'ASF.FS.61416995' 'ASF.FS.60101875' 'ASF.FS.60350164'
 'ASF.FS.60101029' 'ASF.FS.60101107' 'ASF.FS.60884516' 'ASF.FS.60276759'
 'ASF.FS.60101110' 'ASF.FS.60340640' 'ASF.FS.60101112' 'ASF.FS.60101103'
 'ASF.FS.60622145' 'ASF.FS.60101115' 'ASF.FS.60699501' 'ASF.FS.60101100'
 'ASF.FS.60101114' 'ASF.FS.61505636' 'ASF.FS.60101096' 'ASF.FS.60624870'
 'ASF.FS.60103273' 'ASF.FS.60262678' 'ASF.FS.60752027' 'ASF.FS.60100149'
 'ASF.FS.60100106' 'ASF.FS.60100939' 'ASF.FS.60100067' 'ASF.FS.60979461'
 'ASF.FS.60099467' 'ASF.FS.60113919' 'ASF.FS.61473328' 'ASF.FS.60927357'
 'ASF.FS.60100194' 'ASF.FS.60100198' 'ASF.FS.60101646' 'ASF.FS.60099809'
 'ASF.FS.60572737' 'ASF.FS.60101001' 'ASF.FS.60844979' 'ASF.FS.60102710'
 'ASF.FS.60100936' 'ASF.FS.60319784' 'ASF.FS.61486543' 'ASF.FS.60783506'
 'ASF.FS.60639476' 'ASF.FS.60101042' 'ASF.FS.60101035' 'ASF.FS.60101038'
 'ASF.FS.60101051' 'ASF.FS.60614436' 'ASF.FS.60101083' 'ASF.FS.60101047'
 'ASF.FS.60101074' 'ASF.FS.60101076' 'ASF.FS.60101053' 'ASF.FS.60101080'
 'ASF.FS.61084629' 'ASF.FS.60475161' 'ASF.FS.61369112' 'ASF.FS.61071924'
 'ASF.FS.60100088' 'ASF.FS.60102753' 'ASF.FS.60534460' 'ASF.FS.60100990'
 'ASF.FS.60099146' 'ASF.FS.60099977' 'ASF.FS.60826603' 'ASF.FS.60103007'
 'ASF.FS.61027806' 'ASF.FS.60298108' 'ASF.FS.60294169' 'ASF.FS.61532152'
 'ASF.FS.60101710' 'ASF.FS.61056111' 'ASF.FS.60102743' 'ASF.FS.60100192'
 'ASF.FS.60100927' 'ASF.FS.60101123' 'ASF.FS.60116732' 'ASF.FS.60099472'
 'ASF.FS.60102756' 'ASF.FS.60101072' 'ASF.FS.61485635' 'ASF.FS.60099954'
 'ASF.FS.60824737' 'ASF.FS.60903051' 'ASF.FS.61388341' 'ASF.FS.60442605'
 'ASF.FS.60107297' 'ASF.FS.60291172' 'ASF.FS.60386753' 'ASF.FS.60099972'
 'ASF.FS.60314581' 'ASF.FS.61511729' 'ASF.FS.60534516' 'ASF.FS.60201074'
 'ASF.FS.60738149' 'ASF.FS.60700933' 'ASF.FS.60100921' 'ASF.FS.60293976'
 'ASF.FS.60103009' 'ASF.FS.60101130' 'ASF.FS.60099788' 'ASF.FS.61252812'
 'ASF.FS.60100919' 'ASF.FS.60129513' 'ASF.FS.60443322' 'ASF.FS.60433684'
 'ASF.FS.60134975' 'ASF.FS.60100163' 'ASF.FS.60100155' 'ASF.FS.60483139'
 'ASF.FS.60099797' 'ASF.FS.60686250' 'ASF.FS.60100079' 'ASF.FS.60779058'
 'ASF.FS.60100124' 'ASF.FS.60100965' 'ASF.FS.60452365' 'ASF.FS.60100082'
 'ASF.FS.60278648' 'ASF.FS.61191721' 'ASF.FS.60101697' 'ASF.FS.60099126'
 'ASF.FS.61178022' 'ASF.FS.60100090' 'ASF.FS.60509264' 'ASF.FS.61343857'
 'ASF.FS.61241398' 'ASF.FS.60100213' 'ASF.FS.60642274' 'ASF.FS.60100019'
 'ASF.FS.61527403' 'ASF.FS.60397572' 'ASF.FS.61325745' 'ASF.FS.61260783'
 'ASF.FS.60103037' 'ASF.FS.60099966' 'ASF.FS.61079026' 'ASF.FS.60101657'
 'ASF.FS.60101658' 'ASF.FS.60101659' 'ASF.FS.60100195' 'ASF.FS.60103014'
 'ASF.FS.60101120' 'ASF.FS.60101134' 'ASF.FS.60099790' 'ASF.FS.60222057'
 'ASF.FS.60222149' 'ASF.FS.61076776' 'ASF.FS.60101033' 'ASF.FS.60532154'
 'ASF.FS.60099807' 'ASF.FS.60102759' 'ASF.FS.60103038' 'ASF.FS.60101652'
 'ASF.FS.60514718' 'ASF.FS.60100164' 'CBC.FS.00000013' 'CBC.FS.00000016'
 'CBC.FS.00000022' 'CBC.FS.00000023' 'CBC.FS.00000024' 'CBC.FS.60393769'
 'CBC.FS.60469804' 'CBC.FS.60507329' 'CBC.FS.60609961' 'CBC.FS.60710661'
 'CBC.FS.60986932' 'CBC.FS.61012452' 'CBC.FS.61110894' 'CBC.FS.61127584'
 'CBC.FS.61185101' 'CBC.FS.61222809' 'CBC.FS.61240082' 'CBC.FS.61310062'
 'CBC.FS.61352372' 'CBC.FS.61386648' 'CBC.FS.61465616' 'HAC.FS.00000008'
 'HAC.FS.00000175' 'HAC.FS.00000080' 'HAC.FS.00000096' 'HAC.FS.60075769'
 'HAC.FS.00000023' 'HAC.FS.00000128' 'HAC.FS.00000056' 'SI.FS.00000191'
 'SI.FS.00000204' 'SI.FS.00000205' 'SI.FS.00003484' 'SI.FS.00004412'
 'SI.FS.00004414' 'SI.FS.00004417' 'SI.FS.00008877']

In [10]:
print(type(null_lat_ids))

<class 'numpy.ndarray'>

In [13]:
asf = 0
cbc = 0
hac = 0
si = 0
no = 0

for id in null_lat_ids:
    if "ASF" in id:
        asf += 1
    elif "CBC" in id:
        cbc += 1
    elif "HAC" in id:
        hac += 1
    elif "SI" in id:
        si += 1
    else:
        no += 1

print(f"ASF = {asf} \nCBC = {cbc} \nHAC = {hac} \nSI = {si} \nNan = {no}")

ASF = 314
CBC = 21
HAC = 8
SI = 8
Nan = 0